const actionTypes = {
  // Stories action types
  SET_MY_STORIES: 'SET_MY_STORIES',
  SET_MY_STORIES_FETCH_STATE: 'SET_MY_STORIES_FETCH_STATE',
  SET_ALL_STORIES: 'SET_ALL_STORIES',
  SET_ALL_STORIES_FETCH_STATE: 'SET_ALL_STORIES_FETCH_STATE',
  // User action types
  SET_USER: 'SET_USER',
  SET_USER_FETCH_STATE: 'SET_USER_FETCH_STATE'
};

export default actionTypes;
